<a href="https://colab.research.google.com/github/nazirumar/OpenCv_Projects/blob/main/ineurolearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.12.0


In [74]:
eyes = tf.eye(5, batch_shape=[3])
eyes

<tf.Tensor: shape=(3, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [82]:
eyes = tf.eye(2,5)
eyes

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)>

In [95]:
zero1 = tf.zeros([10,10])
zero1
zero2 = tf.zeros([10,10])
zero2
print(zero2.shape)
print(zero1.shape)

(10, 10)
(10, 10)


In [97]:
zero1.ndim

2

In [107]:
fills = tf.fill([3, 5], 9)
fills

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]], dtype=int32)>

In [108]:
one = tf.ones([10,10])
one

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [115]:
var = tf.constant([[1,2,3], [5,6,7]])
zero_lk = tf.zeros_like(var)
zero_lk

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [117]:
size = tf.size(var)
size

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [119]:
rank = tf.rank(var)
rank

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Random**

In [156]:
tf.random.set_seed(5);
random =tf.random.normal([20], 0, 1, tf.float32)
random

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([-0.18030666, -0.95028627, -0.03964049, -0.7425406 ,  1.3231523 ,
       -0.61854804,  0.8540664 , -0.08899953,  2.4488697 ,  0.762508  ,
        1.2659615 ,  0.9801489 ,  1.5293121 , -0.57500345,  0.8987044 ,
       -1.250801  , -0.8604956 ,  1.260746  , -0.6830498 ,  0.02615766],
      dtype=float32)>

In [198]:
tf.random.set_seed(2)
uniform = tf.random.uniform([10],  minval=-1, maxval=2)
uniform

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.5592927 ,  0.3927703 , -0.3253007 ,  0.05866539,  1.9572225 ,
        1.9973071 ,  0.69466436, -0.5087477 ,  1.9670806 ,  1.0442419 ],
      dtype=float32)>

In [214]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)




<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

**Math**

In [222]:
var = tf.constant([[2,3,4,5,6], 
                   [2,6,8,9,4]
                   ])
argmax = tf.math.argmax(var, 1)
print(argmax)

var = tf.constant([[2,3,4,5,6], 
                   [6,2,8,9,4]
                   ])
argmin = tf.math.argmin(var, 1)
print(argmin)

tf.Tensor([4 3], shape=(2,), dtype=int64)
tf.Tensor([0 1], shape=(2,), dtype=int64)


In [225]:
var1 = tf.constant([2,3,4,5,6,5])
reduce_sum = tf.math.reduce_sum(var1)
print(reduce_sum)
var2 = tf.constant([[2,3,4,5,6,5], [10,10,10,10,10,10]])
reduce_sum = tf.math.reduce_sum(var2)
print(reduce_sum)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(85, shape=(), dtype=int32)


In [230]:
var = tf.constant([0,3,90,2, 300])
top_k = tf.math.top_k(var, k=3)
print(top_k)

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([300,  90,   3], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 1], dtype=int32)>)


**LinearAlgebra**

In [240]:
var  = tf.constant([[ 0,  1,  2, 3],
               [-1,  0,  1, 2],
               [-2, -1,  0, 1],
               [-3, -2, -1, 0]])
linag1 = tf.linalg.band_part(var, 1, 1)
linag2 = tf.linalg.band_part(var, 2, 1)
print(linag1)
print(linag2)
# https://www.tensorflow.org/api_docs/python/tf/linalg/band_part

tf.Tensor(
[[ 0  1  0  0]
 [-1  0  1  0]
 [ 0 -1  0  1]
 [ 0  0 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  1  0  0]
 [-1  0  1  0]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)


In [241]:
m0 = tf.random.normal(shape=[2, 3])
m1 = tf.random.normal(shape=[3, 5])
e = tf.einsum('ij,jk->ik', m0, m1)
# output[i,k] = sum_j m0[i,j] * m1[j, k]
print(e.shape)


(2, 5)


In [250]:
squeeze = tf.constant([[[1,2,3,4], [2,4,5,6], [7,2,7,8]]])
print(squeeze.shape)
print(tf.squeeze(squeeze).shape)

(1, 3, 4)
(3, 4)


In [258]:
var = tf.constant([[1,23,40], 
                  [10,22,11]
                   ])
print(var)
expand_dim = tf.expand_dims(var, 0)
print(expand_dim)

tf.Tensor(
[[ 1 23 40]
 [10 22 11]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 1 23 40]
  [10 22 11]]], shape=(1, 2, 3), dtype=int32)


In [309]:
var = tf.range(1,201)
print(var.shape)
reshape = tf.reshape(var, shape=(5,5,8))
print(reshape.shape)


(200,)
(5, 5, 8)


In [275]:
x_1 = tf.constant([[1,23,40], 
                  [10,22,11]
                   ])
x_2 = tf.constant([[10,3,4], 
                  [11,2,1]
                   ])
print(tf.concat([x_1, x_2], 1)) # Columns
print(tf.concat([x_1, x_2], 0)) # Rows

tf.Tensor(
[[ 1 23 40 10  3  4]
 [10 22 11 11  2  1]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[ 1 23 40]
 [10 22 11]
 [10  3  4]
 [11  2  1]], shape=(4, 3), dtype=int32)


In [277]:
x_1 = tf.constant([[1,23,40], 
                  [10,22,11]
                   ])
x_2 = tf.constant([[10,3,4], 
                  [11,2,1]
                   ])
x_3 = tf.constant([[10,3,4], 
                  [11,2,1]
                   ])
print(tf.stack([x_1, x_2, x_3], 1)) # Columns
print(tf.stack([x_1, x_2, x_3], 0)) # Rows

tf.Tensor(
[[[ 1 23 40]
  [10  3  4]
  [10  3  4]]

 [[10 22 11]
  [11  2  1]
  [11  2  1]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[ 1 23 40]
  [10 22 11]]

 [[10  3  4]
  [11  2  1]]

 [[10  3  4]
  [11  2  1]]], shape=(3, 2, 3), dtype=int32)


In [283]:
print("+++++++++++  CONSTANT  +++++++++++ ")
x_1 = tf.constant([[10,3,4], 
                  [11,2,1]
                   ])
paddings = tf.constant([[1, 1,], [2, 2]])
print(tf.pad(x_1, paddings, "CONSTANT"), '\n')

print("+++++++++++  REFLECT  +++++++++++ ")

x_2 = tf.constant([[10,3,4], 
                  [11,2,1]
                   ])
paddings = tf.constant([[1, 1,], [2, 2]])
print(tf.pad(x_2, paddings, 'REFLECT'), '\n')

print("+++++++++++  SYMMETRIC  +++++++++++ ")

x_3 = tf.constant([[10,3,4], 
                  [11,2,1]
                   ])
paddings = tf.constant([[1, 1,], [2, 2]])
print(tf.pad(x_3, paddings, "SYMMETRIC"), '\n')

+++++++++++  CONSTANT  +++++++++++ 
tf.Tensor(
[[ 0  0  0  0  0  0  0]
 [ 0  0 10  3  4  0  0]
 [ 0  0 11  2  1  0  0]
 [ 0  0  0  0  0  0  0]], shape=(4, 7), dtype=int32) 

+++++++++++  REFLECT  +++++++++++ 
tf.Tensor(
[[ 1  2 11  2  1  2 11]
 [ 4  3 10  3  4  3 10]
 [ 1  2 11  2  1  2 11]
 [ 4  3 10  3  4  3 10]], shape=(4, 7), dtype=int32) 

+++++++++++  SYMMETRIC  +++++++++++ 
tf.Tensor(
[[ 3 10 10  3  4  4  3]
 [ 3 10 10  3  4  4  3]
 [ 2 11 11  2  1  1  2]
 [ 2 11 11  2  1  1  2]], shape=(4, 7), dtype=int32) 



In [294]:
params = tf.constant([[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(tf.gather(params, [[1], [3]]))

tf.Tensor(
[[[10. 11. 12.]]

 [[30. 31. 32.]]], shape=(2, 1, 3), dtype=float32)


In [295]:
params = tf.constant([[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(tf.gather_nd(params, [[1], [3]]))

tf.Tensor(
[[10. 11. 12.]
 [30. 31. 32.]], shape=(2, 3), dtype=float32)


In [ ]:
params = tf.constant([[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(tf.ragged())

In [298]:
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[True, False, True], [False, True, False], [True, False, False]]).to_list()

[[1, 3], [5], [7]]

In [308]:
string = tf.strings.join(['albc','def'], name='k', separator=' ').numpy()
print(string)

b'albc def'
